### ISSUE TITLE
Got /root/develop/WebVtk/source/MPRView.h:7:29: fatal error: vtkSmartPointer.h: No such file or directory

### ISSUE THREAD

**Issue by TMKevin** [xikuibin/WebVtk#1]
Ubuntu 16.04.4
Wt: Wt 3.3.6 built from source code. Saved in WT_SDK_DIR
Vtk: Vtk 7.0 built from source code. All files are saved in VTK_LOCALINSTALL_DIR.

I got the following error when trying to build Webtk.
In file included from /root/develop/WebVtk/source/MPRWidget.h:3:0,
                 from /root/develop/WebVtk/source/WebVtk.C:22:
/root/develop/WebVtk/source/MPRView.h:7:29: fatal error: vtkSmartPointer.h: No such file or directory
compilation terminated.
CMakeFiles/WebVtk.dir/build.make:62: recipe for target 'CMakeFiles/WebVtk.dir/WebVtk.C.o' failed
make[2]: *** [CMakeFiles/WebVtk.dir/WebVtk.C.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/WebVtk.dir/all' failed
make[1]: *** [CMakeFiles/WebVtk.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by xikuibin** [comment]
The file shall be at this location ${VTK_LOCALINSTALL_DIR}/include/vtk-7.0/vtkSmartPointer.h.
The ${VTK_LOCALINSTALL_DIR} contents should be created by `make install` after building vtk by `make`. 
Otherwise, you could also change the cmakelist.txt according to your enviorment.
